#AWS S3
cloud:
  aws:
    s3:
      bucket: ggudockbucket
    credentials:
      access-key: AKIA5FTZD5PKC6IHRXQY
      secret-key:
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false