spring:
  profiles:
    include: aws
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
# swagger
springdoc:
  api-docs:
    path: /api-docs # API ?? ?? ??
    groups:
      enabled: true
  swagger-ui:
    path: / # Swagger-ui ??
    enabled: true
    groups-order: asc
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: true
  override-with-generic-response: false
  model-and-view-allowed: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json